#!/usr/bin/with-contenv bash


i=/opt/jellyseerr/config

[[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]] && \
    rm -Rf "$i" && \
    ln -s /config/"$(basename "$i")" "$i"
[[ -e "$i" && ! -L "$i" ]] && \
    mv "$i" /config/"$(basename "$i")" && \
    ln -s /config/"$(basename "$i")" "$i"

# permissions
chown -R abc:abc \
	/config
